name: '${project.name}'
version: '${project.version}'
main: de.ree.theos.bq.TRBQAddon
api-version: '1.18'
authors: [ TheosRee ]
description: BetonQuest Addon for development and experimental features.
website: https://github.com/TheosRee/BQAddon
depend:
  - BetonQuest
