name: Release from Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/TR-BQ-Addon-*.jar"
          bodyFile: "CHANGELOG.md"
